# Generated by Django 5.0.2 on 2024-05-18 21:40

from django.db import migrations
from django.conf import settings


def create_initial_objects(apps, schema_editor):
    """Create initial database objects from settings"""
    for obj in settings.INITIAL_OBJECTS:
        Model = apps.get_model(obj["app"], obj["model"])
        obj_list = [Model(**kwargs) for kwargs in obj["kwargs"]]
        Model.objects.bulk_create(obj_list)


class Migration(migrations.Migration):
    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_objects)
    ]
