# Generated by Django 5.2.4 on 2025-08-01 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20240522_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enter',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enter',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enter',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storage')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.IntegerField(default=0)),
                ('actual_amount', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.inventorycheck')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.item')),
            ],
            options={
                'verbose_name': 'Позиция инвентаризации',
                'verbose_name_plural': 'Позиции инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.item')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storage')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
            },
        ),
    ]
