# Generated by Django 5.2.4 on 2025-08-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_enter_created_at_enter_document_number_enter_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycheck',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20),
        ),
    ]
