# Generated by Django 5.2.4 on 2025-08-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_inventorycheck_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_items', to='stores.storage'),
        ),
    ]
