# Generated by Django 5.2.4 on 2025-08-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_5_fix_default_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='default_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_items', to='stores.storage'),
        ),
    ]
