# Generated by Django 5.2.4 on 2025-08-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006a_ensure_default_storage'),
        ('stores', '0007_alter_item_default_storage'),
    ]

    operations = [
    ]
