services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    networks:
      - nexus-merchant-network
    volumes:
      - ./database.sqlite3:/app/database.sqlite3
      - ./src/media:/app/src/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

networks:
  nexus-merchant-network:
    name: nexus-merchant-network
