# Generated by Django 5.2.4 on 2025-07-31 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_taskcategory_alter_order_options_and_more'),
        ('stores', '0002_auto_20240522_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('customer', 'Клиент'), ('supplier', 'Поставщик'), ('partner', 'Партнер')], default='customer', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('blocked', 'Заблокирован')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
